#!/bin/bash
function hashtree() {
(ls -A ;echo "$(pwd)") | sha1sum | awk '{print $1}';
}
function hashfile() {
    (cat $1;echo $1;) | sha1sum | awk '{print $1}'
}
echo "tree $(hashtree $(pwd))" > a
if [ $(cat $(pwd)/.xing/head |wc -l) -gt 0 ]
then
echo "parent $(cat $(pwd)/.xing/head)">>a;
fi
echo "Author $USER">>a
echo >> a
echo $1 >> a
b=$(hashfile a)
cp a $(pwd)/.xing/objects/$b
rm a
echo $b>$(pwd)/.xing/head
